### ISSUE TITLE
array.reverse! not accepted - it should be accepted

### ISSUE THREAD

**Issue by SJeannie** [learn-co-curriculum/array-methods-lab#9]
I can use array.sort! to return the sorted array 

Similarly, I should be able to use array.reverse! to return the array with its contents reversed - but I can't!  

The module requires that I use **.reverse**, and the test file doesn't dictate which method to use, so I'm puzzled as to why I can't use .reverse! .

![capture](https://user-images.githubusercontent.com/26906650/42705981-d61cc028-869a-11e8-8d9a-b02c5473f6e7.PNG)

**Comment by SJeannie** [comment]
Second issue: 
When I tried to create this issue from Learn (ask a question --> create issue), it said that I'm in the Speaking Grandma lab (wrong page/tab title for the module, too).

**Comment by morgvanny** [comment]
#reverse! is destructive, so it not only returns the reversed array, but also changes the value of the original array to be reversed by default. Sorry for any confusion caused by vagueness! Generally, you only want to add the ! if you particularly want to do it destructively, but avoid it otherwise.
